vimenv

diff --git a/libexec/vimenv b/libexec/vimenv
--- a/libexec/vimenv
+++ b/libexec/vimenv
@@ -3,11 +3,11 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export VIMENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$VIMENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
@@ -30,39 +30,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${VIMENV_ROOT}" ]; then
+  VIMENV_ROOT="${HOME}/.vimenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  VIMENV_ROOT="${VIMENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export VIMENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${VIMENV_DIR}" ]; then
+  VIMENV_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$VIMENV_DIR" 2>/dev/null || {
+    echo "vimenv: cannot change working directory to \`$VIMENV_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  VIMENV_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export VIMENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${VIMENV_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${VIMENV_HOOK_PATH}:${VIMENV_ROOT}/vimenv.d:/usr/local/etc/vimenv.d:/etc/vimenv.d:/usr/lib/vimenv/hooks"
+for plugin_hook in "${VIMENV_ROOT}/plugins/"*/etc/vimenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export VIMENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -70,15 +70,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(vimenv---version)\n$(vimenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec vimenv---version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "vimenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "vimenv: no such command \`$command'" >&2
     exit 1
   fi
 
diff --git a/libexec/vimenv-which b/libexec/vimenv-which
--- a/libexec/vimenv-which
+++ b/libexec/vimenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: vimenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that vimenv will invoke when
 # you run the given command.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$VIMENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide vimenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec vimenv shims --short
 fi
 
 expand_path() {
@@ -48,31 +48,31 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+VIMENV_VERSION="$(vimenv-version-name)"
+VIMENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+if [ -z "$VIMENV_COMMAND" ]; then
+  vimenv-help --usage which >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
+if [ "$VIMENV_VERSION" = "system" ]; then
+  PATH="$(remove_from_path "${VIMENV_ROOT}/shims")"
+  VIMENV_COMMAND_PATH="$(command -v "$VIMENV_COMMAND" || true)"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  VIMENV_COMMAND_PATH="${VIMENV_ROOT}/versions/${VIMENV_VERSION}/bin/${VIMENV_COMMAND}"
 fi
 
-for script in $(rbenv-hooks which); do
+for script in $(vimenv-hooks which); do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$VIMENV_COMMAND_PATH" ]; then
+  echo "$VIMENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "vimenv: $VIMENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(vimenv-whence "$VIMENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
       echo "The \`$1' command exists in these Ruby versions:"
