edit libexec/*

diff --git a/libexec/vimenv-prefix b/libexec/vimenv-prefix
--- a/libexec/vimenv-prefix
+++ b/libexec/vimenv-prefix
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-# Summary: Display prefix for a Ruby version
+# Summary: Display prefix for a vim version
 # Usage: vimenv prefix [<version>]
 #
-# Displays the directory where a Ruby version is installed. If no
+# Displays the directory where a vim version is installed. If no
 # version is given, `vimenv prefix' displays the location of the
 # currently selected version.
 
@@ -22,10 +22,14 @@ elif [ -z "$VIMENV_VERSION" ]; then
 fi
 
 if [ "$VIMENV_VERSION" = "system" ]; then
-  RUBY_PATH="$(vimenv-which ruby)"
-  RUBY_PATH="${RUBY_PATH%/*}"
-  echo "${RUBY_PATH%/bin}"
-  exit
+  if VIM_PATH="$(vimenv-which vim)"; then
+    VIM_PATH="${VIM_PATH%/*}"
+    VIMENV_PREFIX_PATH="${VIM_PATH%/bin}"
+    echo "${VIMENV_PREFIX_PATH:-/}"
+    exit
+  fi
+  echo "vimenv: system version not found in PTH" >&2
+  exit 1
 fi
 
 VIMENV_PREFIX_PATH="${VIMENV_ROOT}/versions/${VIMENV_VERSION}"
